name: nmr
channels:
  - conda-forge
  - bioconda
  - jmrohwer
  - defaults
dependencies:
  - numpy
  - scipy
  - ipykernel
  - matplotlib
  - nmrpy
  - rdkit
  - xlsxwriter
  - ipykernel
  - pandas=2.1
  - pyarrow
  - jupyter
  - openpyxl
